export const lightPalette = {
  primary: '#8b5cf6',
  secondary: '#a78bfa',
  background: 'bg-gradient-to-br from-gray-50 to-purple-100',
  text: 'text-gray-800',
  cardBg: 'bg-white',
  cardBorder: 'border border-purple-200',
  inputBg: 'bg-white',
  inputBorder: 'border-purple-300',
  buttonBg: 'bg-white',
  buttonText: 'text-purple-400',
  buttonBorder: 'border-purple-400',
  buttonHover: 'hover:bg-white hover:text-purple-400',
  priceBadgeBg: 'bg-purple-100',
  priceBadgeText: 'text-purple-800',
  priceBadgeBorder: 'border-purple-200',
  titleText: 'text-gray-900',
  subtitleText: 'text-gray-600',
  footerText: 'text-gray-600',
  footerIcon: 'text-purple-600',
  errorBg: 'bg-red-100',
  errorText: 'text-red-800',
  titleGradient: 'from-purple-600 to-pink-500',
};

export const darkPalette = {
  primary: '#3b82f6',
  secondary: '#60a5fa',
  background: 'bg-gradient-to-br from-gray-900 to-slate-800',
  text: 'text-gray-100',
  cardBg: 'bg-gray-800',
  cardBorder: 'border border-blue-500',
  inputBg: 'bg-gray-700',
  inputBorder: 'border-blue-400',
  buttonBg: 'bg-blue-600',
  buttonText: 'text-blue-400',
  buttonBorder: 'border-blue-400',
  buttonHover: 'hover:bg-blue-200 hover:text-white',
  priceBadgeBg: 'bg-blue-600',
  priceBadgeText: 'text-white',
  priceBadgeBorder: 'border-blue-500',
  titleText: 'text-blue-200',
  subtitleText: 'text-gray-300',
  footerText: 'text-gray-300',
  footerIcon: 'text-blue-300',
  errorBg: 'bg-red-900/50',
  errorText: 'text-red-200',
  titleGradient: 'from-blue-400 to-cyan-300',
};
